# Generated by Django 5.0.14 on 2026-04-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('buksa', 'Buksa'), ('hotgoss', 'HotGoss'), ('samesky', 'SameSky'), ('taskmatic', 'Taskmatic')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('button_label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'timestamp'], name='pages_conve_product_a6c667_idx')],
            },
        ),
    ]
