# Generated by Django 4.2.30 on 2026-04-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversion',
            new_name='ads_set_v1__product_eb513a_idx',
            old_name='pages_conve_product_a6c667_idx',
        ),
        migrations.AlterModelTable(
            name='conversion',
            table='ads_set_v1_pages_conversion',
        ),
    ]
